
public class Image 
{

	/**
	 * Class to store the PPM and ASCII value of image
	 */
	
	// array to store the PPM and the output ASCII value
	protected int ppmValue [][];
	protected char output [];
	// to store the number of pixel in a file
	int inputLength;
    
	
	// default constructor
	Image()
	{
		ppmValue = new int[0][0];
		output = new char[0];
	}
	
	
	// parameterized constructor
	Image(int width, int length)
	{
		inputLength = width*length;
		ppmValue = new int [3][inputLength];
		output = new char[inputLength];
	}
	
	
}
